// Copyright (c) 2014 Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Inital yacc source generated by ebnf2y[1]
// at 2013-10-04 23:10:47.861401015 +0200 CEST
//
//  $ ebnf2y -o ql.y -oe ql.ebnf -start StatementList -pkg ql -p _
//
// CAUTION: If this file is a Go source file (*.go), it was generated
// automatically by '$ go tool yacc' from a *.y file - DO NOT EDIT in that case!
//
//   [1]: http://github.com/cznic/ebnf2y

package ql

import __yyfmt__ "fmt"

import (
	"fmt"

	"github.com/cznic/mathutil"
)

type yySymType struct {
	yys  int
	line int
	col  int
	item interface{}
	list []interface{}
}

const add = 57346
const alter = 57347
const and = 57348
const andand = 57349
const andnot = 57350
const as = 57351
const asc = 57352
const begin = 57353
const between = 57354
const bigIntType = 57355
const bigRatType = 57356
const blobType = 57357
const boolType = 57358
const by = 57359
const byteType = 57360
const column = 57361
const commit = 57362
const complex128Type = 57363
const complex64Type = 57364
const create = 57365
const deleteKwd = 57366
const desc = 57367
const distinct = 57368
const drop = 57369
const durationType = 57370
const eq = 57371
const exists = 57372
const falseKwd = 57373
const floatType = 57374
const float32Type = 57375
const float64Type = 57376
const floatLit = 57377
const from = 57378
const ge = 57379
const group = 57380
const identifier = 57381
const ifKwd = 57382
const imaginaryLit = 57383
const in = 57384
const index = 57385
const insert = 57386
const intType = 57387
const int16Type = 57388
const int32Type = 57389
const int64Type = 57390
const int8Type = 57391
const into = 57392
const intLit = 57393
const is = 57394
const le = 57395
const limit = 57396
const lsh = 57397
const neq = 57398
const not = 57399
const null = 57400
const offset = 57401
const on = 57402
const order = 57403
const oror = 57404
const qlParam = 57405
const rollback = 57406
const rsh = 57407
const runeType = 57408
const selectKwd = 57409
const stringType = 57410
const stringLit = 57411
const tableKwd = 57412
const timeType = 57413
const transaction = 57414
const trueKwd = 57415
const truncate = 57416
const uintType = 57417
const uint16Type = 57418
const uint32Type = 57419
const uint64Type = 57420
const uint8Type = 57421
const unique = 57422
const update = 57423
const values = 57424
const where = 57425

var yyToknames = []string{
	"add",
	"alter",
	"and",
	"andand",
	"andnot",
	"as",
	"asc",
	"begin",
	"between",
	"bigIntType",
	"bigRatType",
	"blobType",
	"boolType",
	"by",
	"byteType",
	"column",
	"commit",
	"complex128Type",
	"complex64Type",
	"create",
	"deleteKwd",
	"desc",
	"distinct",
	"drop",
	"durationType",
	"eq",
	"exists",
	"falseKwd",
	"floatType",
	"float32Type",
	"float64Type",
	"floatLit",
	"from",
	"ge",
	"group",
	"identifier",
	"ifKwd",
	"imaginaryLit",
	"in",
	"index",
	"insert",
	"intType",
	"int16Type",
	"int32Type",
	"int64Type",
	"int8Type",
	"into",
	"intLit",
	"is",
	"le",
	"limit",
	"lsh",
	"neq",
	"not",
	"null",
	"offset",
	"on",
	"order",
	"oror",
	"qlParam",
	"rollback",
	"rsh",
	"runeType",
	"selectKwd",
	"stringType",
	"stringLit",
	"tableKwd",
	"timeType",
	"transaction",
	"trueKwd",
	"truncate",
	"uintType",
	"uint16Type",
	"uint32Type",
	"uint64Type",
	"uint8Type",
	"unique",
	"update",
	"values",
	"where",
}
var yyStatenames = []string{}

const yyEOFCode = 1
const yyErrCode = 2
const yyMaxDepth = 200

var yyExca = []int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyNprod = 193
const yyPrivate = 57344

var yyTokenNames []string
var yyStates []string

const yyLast = 863

var yyAct = []int{

	214, 213, 249, 302, 167, 293, 176, 279, 224, 61,
	257, 166, 110, 230, 179, 14, 75, 62, 41, 231,
	59, 125, 143, 262, 58, 28, 56, 161, 265, 125,
	63, 139, 140, 141, 142, 238, 125, 154, 125, 57,
	315, 153, 289, 288, 181, 125, 111, 307, 44, 306,
	240, 46, 297, 48, 308, 50, 52, 131, 286, 108,
	284, 241, 283, 246, 276, 269, 273, 263, 118, 145,
	215, 244, 227, 251, 138, 159, 248, 236, 119, 146,
	229, 300, 133, 181, 226, 187, 160, 129, 119, 122,
	116, 182, 250, 271, 254, 219, 124, 132, 135, 165,
	119, 137, 130, 25, 30, 35, 169, 40, 29, 32,
	144, 147, 148, 149, 139, 140, 141, 142, 174, 33,
	172, 139, 140, 141, 142, 57, 25, 177, 170, 163,
	182, 125, 36, 134, 136, 281, 303, 175, 127, 173,
	239, 190, 117, 193, 194, 195, 196, 197, 198, 186,
	184, 183, 64, 294, 210, 192, 191, 199, 200, 201,
	202, 216, 37, 189, 45, 112, 220, 42, 51, 42,
	47, 272, 260, 222, 203, 204, 205, 206, 207, 208,
	209, 42, 223, 217, 221, 185, 115, 49, 17, 235,
	225, 125, 259, 188, 18, 123, 34, 171, 234, 237,
	120, 2, 113, 19, 39, 168, 20, 21, 295, 282,
	22, 312, 243, 233, 128, 261, 299, 270, 155, 156,
	157, 158, 253, 218, 111, 114, 313, 23, 252, 178,
	43, 162, 247, 16, 15, 1, 151, 53, 264, 38,
	13, 232, 268, 256, 255, 180, 73, 24, 266, 311,
	25, 280, 69, 71, 291, 121, 12, 26, 150, 277,
	258, 55, 274, 275, 27, 126, 60, 278, 245, 3,
	11, 10, 287, 9, 8, 285, 31, 7, 70, 6,
	228, 212, 152, 5, 290, 164, 292, 177, 109, 296,
	4, 0, 0, 298, 0, 304, 0, 305, 301, 0,
	0, 0, 0, 0, 310, 309, 84, 85, 86, 87,
	314, 88, 0, 0, 89, 90, 0, 0, 0, 0,
	0, 91, 0, 0, 76, 92, 93, 94, 79, 0,
	0, 0, 83, 0, 80, 0, 0, 0, 95, 96,
	97, 98, 99, 0, 81, 0, 0, 0, 0, 0,
	0, 77, 0, 0, 0, 0, 72, 0, 0, 100,
	0, 101, 82, 0, 102, 0, 78, 0, 103, 104,
	105, 106, 107, 0, 0, 0, 0, 0, 0, 74,
	0, 0, 0, 0, 267, 65, 0, 67, 68, 84,
	85, 86, 87, 0, 88, 0, 66, 89, 90, 0,
	0, 0, 0, 0, 91, 0, 0, 76, 92, 93,
	94, 79, 0, 0, 0, 83, 0, 80, 0, 0,
	0, 95, 96, 97, 98, 99, 0, 81, 0, 0,
	0, 0, 0, 0, 77, 0, 0, 0, 0, 72,
	0, 0, 100, 0, 101, 82, 0, 102, 0, 78,
	0, 103, 104, 105, 106, 107, 0, 0, 0, 0,
	0, 0, 74, 0, 0, 0, 0, 242, 65, 0,
	67, 68, 84, 85, 86, 87, 0, 88, 0, 66,
	89, 90, 0, 0, 0, 0, 0, 91, 0, 0,
	76, 92, 93, 94, 79, 0, 0, 0, 83, 0,
	80, 0, 0, 0, 95, 96, 97, 98, 99, 0,
	81, 0, 0, 0, 0, 0, 0, 77, 0, 0,
	0, 0, 72, 0, 0, 100, 0, 101, 82, 0,
	102, 0, 78, 0, 103, 104, 105, 106, 107, 0,
	0, 0, 0, 0, 0, 74, 0, 0, 0, 0,
	0, 65, 0, 67, 68, 84, 85, 86, 87, 0,
	88, 211, 66, 89, 90, 0, 0, 0, 0, 0,
	91, 0, 0, 76, 92, 93, 94, 79, 0, 0,
	0, 83, 0, 80, 0, 0, 0, 95, 96, 97,
	98, 99, 0, 81, 0, 0, 0, 0, 0, 0,
	77, 0, 0, 0, 0, 72, 0, 0, 100, 0,
	101, 82, 0, 102, 0, 78, 0, 103, 104, 105,
	106, 107, 0, 0, 0, 0, 0, 0, 74, 0,
	0, 0, 0, 0, 65, 0, 67, 68, 0, 0,
	0, 54, 0, 0, 0, 66, 84, 85, 86, 87,
	0, 88, 0, 0, 89, 90, 0, 0, 0, 0,
	0, 91, 0, 0, 76, 92, 93, 94, 79, 0,
	0, 0, 83, 0, 80, 0, 0, 0, 95, 96,
	97, 98, 99, 0, 81, 0, 0, 0, 0, 0,
	0, 77, 0, 0, 0, 0, 72, 0, 0, 100,
	0, 101, 82, 0, 102, 0, 78, 0, 103, 104,
	105, 106, 107, 0, 0, 0, 0, 0, 0, 74,
	0, 0, 0, 0, 0, 65, 0, 67, 68, 84,
	85, 86, 87, 0, 88, 0, 66, 89, 90, 0,
	0, 0, 0, 0, 91, 0, 0, 76, 92, 93,
	94, 79, 0, 0, 0, 83, 0, 80, 0, 0,
	0, 95, 96, 97, 98, 99, 0, 81, 0, 0,
	0, 0, 0, 0, 77, 0, 0, 0, 0, 72,
	0, 0, 100, 0, 101, 82, 0, 102, 0, 78,
	0, 103, 104, 105, 106, 107, 84, 85, 86, 87,
	0, 88, 74, 0, 89, 90, 0, 0, 0, 0,
	0, 91, 0, 0, 0, 92, 93, 94, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 95, 96,
	97, 98, 99, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 100,
	0, 101, 0, 0, 102, 0, 0, 0, 103, 104,
	105, 106, 107,
}
var yyPact = []int{

	183, -76, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, 38, 32, -1000,
	39, 160, 62, 112, -1000, 178, 37, 142, 183, 142,
	-1000, 121, 130, -1000, 142, 148, 128, 142, 542, -1000,
	142, 126, -1000, -1000, 198, 147, 4, 85, 17, -1000,
	-1000, 170, 3, 159, -1000, 11, -1000, 129, 207, -1000,
	45, -61, 14, -1000, -49, 716, 716, 716, 716, -1000,
	-1000, -1000, -1000, -1000, 633, 0, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -73, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 17,
	-1000, 15, -1000, 126, 186, 46, 126, 167, -1000, 633,
	142, 36, 126, 44, 633, 633, -1000, 146, 633, -1,
	151, 633, 98, 633, 633, 633, 633, 633, 633, 633,
	633, 633, 633, 633, 633, 633, 633, 633, 633, 633,
	-1000, -1000, -1000, 459, 633, -49, -49, -49, -49, -17,
	633, 144, -1000, -1000, 10, 633, -1000, 783, 126, 143,
	-1000, 142, 69, -1000, -2, -1000, -15, -1000, -5, -1000,
	204, -1000, 59, -1000, 207, -1000, -1000, 633, -9, 633,
	29, -1000, 82, -61, -61, -61, -61, -61, -61, 14,
	14, 14, 14, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-41, 376, -16, -1000, 69, -1000, -24, -1000, -1000, 126,
	69, -1000, -1000, -10, 7, -13, 633, -1000, 9, 5,
	154, -1000, -1000, 133, -78, -20, 633, 22, 633, -1000,
	-1000, 293, -1000, -26, -1000, 8, -1000, -1000, 132, -21,
	126, 126, -23, -1000, 126, -1000, 154, 74, -1000, 192,
	-1000, -25, -1000, -1000, -27, 633, -61, -1000, -33, -1000,
	-1000, 633, -44, -1000, -1000, -1000, -1000, -1000, 74, 99,
	-1000, 191, 126, -1000, -1000, -61, -1000, 69, -1000, -35,
	7, -4, 99, 77, 633, 633, -1000, -38, -40, -1000,
	-32, 77, -1000, 633, 69, 201, -1000, -1000, 633, -1000,
	69, -1000, -1000, -1000, -47, -1000,
}
var yyPgo = []int{

	0, 290, 12, 288, 285, 283, 282, 281, 11, 4,
	6, 280, 279, 278, 277, 276, 274, 8, 273, 271,
	270, 269, 0, 1, 268, 20, 266, 26, 265, 261,
	260, 258, 256, 255, 254, 253, 252, 251, 249, 246,
	152, 9, 17, 14, 245, 241, 240, 15, 239, 237,
	5, 13, 10, 3, 7, 236, 201, 235, 18, 24,
	234, 16, 30, 233, 231, 19, 229, 223, 222, 2,
	217, 216, 215,
}
var yyR1 = []int{

	0, 1, 1, 2, 3, 4, 4, 67, 67, 5,
	6, 7, 7, 8, 9, 10, 11, 11, 68, 68,
	12, 13, 14, 14, 15, 15, 16, 16, 17, 17,
	69, 69, 18, 18, 19, 20, 20, 21, 22, 22,
	23, 24, 24, 70, 70, 25, 25, 25, 25, 25,
	25, 25, 26, 26, 26, 26, 26, 26, 26, 27,
	28, 28, 29, 29, 30, 31, 32, 32, 33, 33,
	34, 34, 71, 71, 35, 35, 35, 35, 35, 35,
	35, 36, 36, 36, 36, 37, 38, 38, 38, 40,
	40, 40, 40, 40, 41, 41, 41, 41, 41, 42,
	42, 42, 42, 42, 42, 42, 42, 39, 39, 43,
	44, 44, 72, 72, 45, 45, 66, 66, 46, 47,
	47, 50, 50, 53, 53, 48, 48, 49, 49, 49,
	51, 51, 52, 52, 54, 54, 55, 55, 55, 55,
	56, 56, 56, 56, 56, 56, 56, 56, 56, 56,
	56, 56, 56, 56, 57, 57, 58, 59, 59, 60,
	61, 61, 61, 61, 61, 61, 61, 61, 61, 61,
	61, 61, 61, 61, 61, 61, 61, 61, 61, 61,
	61, 61, 61, 61, 63, 64, 64, 62, 62, 62,
	62, 62, 65,
}
var yyR2 = []int{

	0, 5, 6, 3, 3, 0, 3, 0, 1, 2,
	3, 0, 1, 2, 1, 3, 0, 3, 0, 1,
	1, 4, 9, 11, 0, 1, 8, 11, 0, 3,
	0, 1, 3, 4, 3, 3, 5, 0, 1, 3,
	3, 0, 3, 0, 1, 1, 5, 6, 5, 6,
	3, 4, 1, 3, 3, 3, 3, 3, 3, 2,
	0, 2, 1, 3, 3, 3, 10, 5, 0, 3,
	0, 5, 0, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 3, 4, 0, 1, 1, 1,
	1, 2, 2, 2, 1, 3, 3, 3, 3, 1,
	3, 3, 3, 3, 3, 3, 3, 1, 3, 2,
	1, 4, 0, 1, 0, 2, 1, 3, 1, 10,
	11, 0, 2, 0, 2, 0, 1, 1, 1, 2,
	0, 1, 0, 1, 0, 1, 3, 4, 4, 5,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 3, 1, 1, 3, 3,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 4, 0, 1, 1, 2, 2,
	2, 2, 2,
}
var yyChk = []int{

	-1000, -57, -56, -21, -1, -5, -12, -14, -16, -18,
	-19, -20, -32, -46, -47, -60, -63, 5, 11, 20,
	23, 24, 27, 44, 64, 67, 74, 81, 101, 70,
	72, -15, 70, 80, 36, 43, 70, 50, -48, 26,
	70, -58, 39, -56, -58, 43, -58, 40, -58, 39,
	-58, 40, -58, -49, 99, -29, -27, -22, -59, -25,
	-26, -41, -42, -62, -40, 92, 103, 94, 95, -36,
	-13, -35, 63, -39, 86, -61, 31, 58, 73, 35,
	41, 51, 69, 39, 13, 14, 15, 16, 18, 21,
	22, 28, 32, 33, 34, 45, 46, 47, 48, 49,
	66, 68, 71, 75, 76, 77, 78, 79, -58, -3,
	-2, -9, 39, 4, 27, 39, 86, 57, -65, 83,
	30, -33, 86, 36, 85, 62, -28, 9, 7, 42,
	57, 12, 52, 37, 88, 53, 89, 56, 29, 92,
	93, 94, 95, 8, 96, 55, 65, 97, 98, 99,
	-31, -55, -6, 90, 86, -40, -40, -40, -40, -22,
	86, 100, -64, -65, -4, 84, -8, -9, 19, 60,
	-8, 30, -22, -58, 82, -47, -10, -9, -66, -43,
	-44, 39, 86, -27, -59, 39, -25, 86, 42, 12,
	-41, 58, 57, -41, -41, -41, -41, -41, -41, -42,
	-42, -42, -42, -62, -62, -62, -62, -62, -62, -62,
	-22, 102, -7, -23, -22, 87, -22, 39, -67, 85,
	-22, -61, -9, 39, -17, -58, 86, 87, -11, 85,
	-51, -65, -45, 9, -47, -23, 86, -41, 6, 58,
	91, 102, 91, -22, 87, -24, 87, -2, 86, -69,
	85, 86, -23, -68, 85, -43, -51, -52, -30, 38,
	39, -72, 101, 87, -23, 6, -41, 91, -22, 91,
	-70, 85, 39, 87, -8, -8, 87, -9, -52, -54,
	-37, 61, 17, 87, 87, -41, 91, -22, 87, 86,
	-17, -34, -54, -50, 54, 17, -10, 87, -69, -71,
	85, -50, -53, 59, -22, -23, 87, 87, 86, -53,
	-22, -38, 10, 25, -23, 87,
}
var yyDef = []int{

	37, -2, 154, 140, 141, 142, 143, 144, 145, 146,
	147, 148, 149, 150, 151, 152, 153, 0, 0, 20,
	24, 0, 0, 0, 118, 125, 0, 0, 37, 0,
	9, 0, 0, 25, 0, 0, 0, 0, 0, 126,
	0, 0, 156, 155, 0, 0, 0, 0, 32, 34,
	35, 0, 68, 0, 127, 128, 62, 60, 38, 157,
	45, 52, 94, 99, 187, 0, 0, 0, 0, 89,
	90, 81, 82, 83, 0, 0, 74, 75, 76, 77,
	78, 79, 80, 107, 160, 161, 162, 163, 164, 165,
	166, 167, 168, 169, 170, 171, 172, 173, 174, 175,
	176, 177, 178, 179, 180, 181, 182, 183, 159, 185,
	5, 0, 14, 0, 0, 0, 0, 0, 33, 0,
	0, 0, 0, 0, 129, 0, 59, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	91, 92, 93, 0, 11, 188, 189, 190, 191, 0,
	0, 0, 184, 186, 7, 0, 1, 0, 0, 0,
	28, 0, 192, 36, 0, 67, 0, 16, 130, 116,
	114, 110, 0, 63, 39, 61, 158, 0, 0, 0,
	0, 50, 0, 53, 54, 55, 56, 57, 58, 95,
	96, 97, 98, 100, 101, 102, 103, 104, 105, 106,
	0, 0, 0, 12, 41, 84, 0, 108, 4, 8,
	3, 13, 2, 0, 30, 0, 0, 69, 18, 130,
	132, 131, 109, 0, 112, 0, 0, 0, 0, 51,
	65, 0, 136, 0, 10, 43, 21, 6, 0, 0,
	31, 0, 0, 15, 19, 117, 132, 134, 133, 0,
	115, 0, 113, 46, 0, 0, 48, 138, 0, 137,
	40, 44, 0, 26, 29, 28, 70, 17, 134, 121,
	135, 0, 0, 111, 47, 49, 139, 42, 22, 0,
	30, 72, 121, 123, 0, 0, 64, 0, 0, 66,
	73, 123, 119, 0, 122, 86, 23, 27, 0, 120,
	124, 85, 87, 88, 0, 71,
}
var yyTok1 = []int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 103, 3, 3, 3, 97, 96, 3,
	86, 87, 99, 95, 85, 94, 100, 98, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 102, 101,
	89, 84, 88, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 90, 3, 91, 92, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 93,
}
var yyTok2 = []int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83,
}
var yyTok3 = []int{
	0,
}

/*	parser for yacc output	*/

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

const yyFlag = -1000

func yyTokname(c int) string {
	// 4 is TOKSTART above
	if c >= 4 && c-4 < len(yyToknames) {
		if yyToknames[c-4] != "" {
			return yyToknames[c-4]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yylex1(lex yyLexer, lval *yySymType) int {
	c := 0
	char := lex.Lex(lval)
	if char <= 0 {
		c = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		c = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			c = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		c = yyTok3[i+0]
		if c == char {
			c = yyTok3[i+1]
			goto out
		}
	}

out:
	if c == 0 {
		c = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(c), uint(char))
	}
	return c
}

func yyParse(yylex yyLexer) int {
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, yyMaxDepth)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yychar := -1
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yychar), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yychar < 0 {
		yychar = yylex1(yylex, &yylval)
	}
	yyn += yychar
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yychar { /* valid shift */
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yychar < 0 {
			yychar = yylex1(yylex, &yylval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yychar {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error("syntax error")
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yychar))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yychar))
			}
			if yychar == yyEOFCode {
				goto ret1
			}
			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:

		{
			yyVAL.item = &alterTableAddStmt{tableName: yyS[yypt-2].item.(string), c: yyS[yypt-0].item.(*col)}
		}
	case 2:

		{
			yyVAL.item = &alterTableDropColumnStmt{tableName: yyS[yypt-3].item.(string), colName: yyS[yypt-0].item.(string)}
		}
	case 3:

		{
			yyVAL.item = assignment{colName: yyS[yypt-2].item.(string), expr: yyS[yypt-0].item.(expression)}
		}
	case 4:

		{
			yyVAL.item = append([]assignment{yyS[yypt-2].item.(assignment)}, yyS[yypt-1].item.([]assignment)...)
		}
	case 5:

		{
			yyVAL.item = []assignment{}
		}
	case 6:

		{
			yyVAL.item = append(yyS[yypt-2].item.([]assignment), yyS[yypt-0].item.(assignment))
		}
	case 9:

		{
			yyVAL.item = beginTransactionStmt{}
		}
	case 10:

		{
			yyVAL.item = yyS[yypt-1].item
		}
	case 11:

		{
			yyVAL.item = []expression{}
		}
	case 12:
		yyVAL.item = yyS[yypt-0].item
	case 13:

		{
			yyVAL.item = &col{name: yyS[yypt-1].item.(string), typ: yyS[yypt-0].item.(int)}
		}
	case 14:
		yyVAL.item = yyS[yypt-0].item
	case 15:

		{
			yyVAL.item = append([]string{yyS[yypt-2].item.(string)}, yyS[yypt-1].item.([]string)...)
		}
	case 16:

		{
			yyVAL.item = []string{}
		}
	case 17:

		{
			yyVAL.item = append(yyS[yypt-2].item.([]string), yyS[yypt-0].item.(string))
		}
	case 20:

		{
			yyVAL.item = commitStmt{}
		}
	case 21:

		{
			yyVAL.item = &conversion{typ: yyS[yypt-3].item.(int), val: yyS[yypt-1].item.(expression)}
		}
	case 22:

		{
			indexName, tableName, columnName := yyS[yypt-5].item.(string), yyS[yypt-3].item.(string), yyS[yypt-1].item.(string)
			yyVAL.item = &createIndexStmt{yyS[yypt-7].item.(bool), indexName, tableName, columnName}
			if indexName == tableName || indexName == columnName {
				yylex.(*lexer).err("index name collision: %s", indexName)
				return 1
			}

			if isSystemName[indexName] || isSystemName[tableName] {
				yylex.(*lexer).err("name is used for system tables: %s", indexName)
				return 1
			}
		}
	case 23:

		{
			indexName, tableName, columnName := yyS[yypt-7].item.(string), yyS[yypt-5].item.(string), yyS[yypt-3].item.(string)
			yyVAL.item = &createIndexStmt{yyS[yypt-9].item.(bool), indexName, tableName, "id()"}
			if yyS[yypt-3].item.(string) != "id" {
				yylex.(*lexer).err("only the built-in function id() can be used in index: %s()", columnName)
				return 1
			}

			if indexName == tableName {
				yylex.(*lexer).err("index name collision: %s", indexName)
				return 1
			}

			if isSystemName[indexName] || isSystemName[tableName] {
				yylex.(*lexer).err("name is used for system tables: %s", indexName)
				return 1
			}
		}
	case 24:

		{
			yyVAL.item = false
		}
	case 25:

		{
			yyVAL.item = true
		}
	case 26:

		{
			nm := yyS[yypt-5].item.(string)
			yyVAL.item = &createTableStmt{tableName: nm, cols: append([]*col{yyS[yypt-3].item.(*col)}, yyS[yypt-2].item.([]*col)...)}
			if isSystemName[nm] {
				yylex.(*lexer).err("name is used for system tables: %s", nm)
				return 1
			}
		}
	case 27:

		{
			nm := yyS[yypt-5].item.(string)
			yyVAL.item = &createTableStmt{ifNotExists: true, tableName: nm, cols: append([]*col{yyS[yypt-3].item.(*col)}, yyS[yypt-2].item.([]*col)...)}
			if isSystemName[nm] {
				yylex.(*lexer).err("name is used for system tables: %s", nm)
				return 1
			}
		}
	case 28:

		{
			yyVAL.item = []*col{}
		}
	case 29:

		{
			yyVAL.item = append(yyS[yypt-2].item.([]*col), yyS[yypt-0].item.(*col))
		}
	case 32:

		{
			yyVAL.item = &truncateTableStmt{yyS[yypt-0].item.(string)}
		}
	case 33:

		{
			yyVAL.item = &deleteStmt{tableName: yyS[yypt-1].item.(string), where: yyS[yypt-0].item.(*whereRset).expr}
		}
	case 34:

		{
			yyVAL.item = &dropIndexStmt{indexName: yyS[yypt-0].item.(string)}
		}
	case 35:

		{
			nm := yyS[yypt-0].item.(string)
			yyVAL.item = &dropTableStmt{tableName: nm}
			if isSystemName[nm] {
				yylex.(*lexer).err("name is used for system tables: %s", nm)
				return 1
			}
		}
	case 36:

		{
			nm := yyS[yypt-0].item.(string)
			yyVAL.item = &dropTableStmt{ifExists: true, tableName: nm}
			if isSystemName[nm] {
				yylex.(*lexer).err("name is used for system tables: %s", nm)
				return 1
			}
		}
	case 37:

		{
			yyVAL.item = nil
		}
	case 38:
		yyVAL.item = yyS[yypt-0].item
	case 39:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation(oror, yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 40:

		{
			yyVAL.item = append([]expression{yyS[yypt-2].item.(expression)}, yyS[yypt-1].item.([]expression)...)
		}
	case 41:

		{
			yyVAL.item = []expression(nil)
		}
	case 42:

		{
			yyVAL.item = append(yyS[yypt-2].item.([]expression), yyS[yypt-0].item.(expression))
		}
	case 45:
		yyVAL.item = yyS[yypt-0].item
	case 46:

		{
			yyVAL.item = &pIn{expr: yyS[yypt-4].item.(expression), list: yyS[yypt-1].item.([]expression)}
		}
	case 47:

		{
			yyVAL.item = &pIn{expr: yyS[yypt-5].item.(expression), not: true, list: yyS[yypt-1].item.([]expression)}
		}
	case 48:

		{
			yyVAL.item = &pBetween{expr: yyS[yypt-4].item.(expression), l: yyS[yypt-2].item.(expression), h: yyS[yypt-0].item.(expression)}
		}
	case 49:

		{
			yyVAL.item = &pBetween{expr: yyS[yypt-5].item.(expression), not: true, l: yyS[yypt-2].item.(expression), h: yyS[yypt-0].item.(expression)}
		}
	case 50:

		{
			yyVAL.item = &isNull{expr: yyS[yypt-2].item.(expression)}
		}
	case 51:

		{
			yyVAL.item = &isNull{expr: yyS[yypt-3].item.(expression), not: true}
		}
	case 52:
		yyVAL.item = yyS[yypt-0].item
	case 53:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation(ge, yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 54:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation('>', yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 55:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation(le, yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 56:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation('<', yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 57:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation(neq, yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 58:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation(eq, yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 59:

		{
			expr, name := yyS[yypt-1].item.(expression), yyS[yypt-0].item.(string)
			if name == "" {
				s, ok := expr.(*ident)
				if ok {
					name = s.s
				}
			}
			yyVAL.item = &fld{expr: expr, name: name}
		}
	case 60:

		{
			yyVAL.item = ""
		}
	case 61:

		{
			yyVAL.item = yyS[yypt-0].item
		}
	case 62:

		{
			yyVAL.item = []*fld{yyS[yypt-0].item.(*fld)}
		}
	case 63:

		{
			l, f := yyS[yypt-2].item.([]*fld), yyS[yypt-0].item.(*fld)
			if f.name != "" {
				if f := findFld(l, f.name); f != nil {
					yylex.(*lexer).err("duplicate field name %q", f.name)
					return 1
				}
			}

			yyVAL.item = append(yyS[yypt-2].item.([]*fld), yyS[yypt-0].item.(*fld))
		}
	case 64:

		{
			yyVAL.item = &groupByRset{colNames: yyS[yypt-0].item.([]string)}
		}
	case 65:

		{
			yyVAL.item = yyS[yypt-1].item
		}
	case 66:

		{
			yyVAL.item = &insertIntoStmt{tableName: yyS[yypt-7].item.(string), colNames: yyS[yypt-6].item.([]string), lists: append([][]expression{yyS[yypt-3].item.([]expression)}, yyS[yypt-1].item.([][]expression)...)}
		}
	case 67:

		{
			yyVAL.item = &insertIntoStmt{tableName: yyS[yypt-2].item.(string), colNames: yyS[yypt-1].item.([]string), sel: yyS[yypt-0].item.(*selectStmt)}
		}
	case 68:

		{
			yyVAL.item = []string{}
		}
	case 69:

		{
			yyVAL.item = yyS[yypt-1].item
		}
	case 70:

		{
			yyVAL.item = [][]expression{}
		}
	case 71:

		{
			yyVAL.item = append(yyS[yypt-4].item.([][]expression), yyS[yypt-1].item.([]expression))
		}
	case 74:
		yyVAL.item = yyS[yypt-0].item
	case 75:
		yyVAL.item = yyS[yypt-0].item
	case 76:
		yyVAL.item = yyS[yypt-0].item
	case 77:
		yyVAL.item = yyS[yypt-0].item
	case 78:
		yyVAL.item = yyS[yypt-0].item
	case 79:
		yyVAL.item = yyS[yypt-0].item
	case 80:
		yyVAL.item = yyS[yypt-0].item
	case 81:

		{
			yyVAL.item = value{yyS[yypt-0].item}
		}
	case 82:

		{
			n := yyS[yypt-0].item.(int)
			yyVAL.item = parameter{n}
			l := yylex.(*lexer)
			l.params = mathutil.Max(l.params, n)
			if n == 0 {
				l.err("parameter number must be non zero")
				return 1
			}
		}
	case 83:

		{
			yyVAL.item = &ident{yyS[yypt-0].item.(string)}
		}
	case 84:

		{
			yyVAL.item = &pexpr{expr: yyS[yypt-1].item.(expression)}
		}
	case 85:

		{
			yyVAL.item = &orderByRset{by: yyS[yypt-1].item.([]expression), asc: yyS[yypt-0].item.(bool)}
		}
	case 86:

		{
			yyVAL.item = true // ASC by default
		}
	case 87:

		{
			yyVAL.item = true
		}
	case 88:

		{
			yyVAL.item = false
		}
	case 89:
		yyVAL.item = yyS[yypt-0].item
	case 90:
		yyVAL.item = yyS[yypt-0].item
	case 91:

		{
			var err error
			if yyVAL.item, err = newIndex(yyS[yypt-1].item.(expression), yyS[yypt-0].item.(expression)); err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 92:

		{
			var err error
			s := yyS[yypt-0].item.([2]*expression)
			if yyVAL.item, err = newSlice(yyS[yypt-1].item.(expression), s[0], s[1]); err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 93:

		{
			x := yylex.(*lexer)
			f, ok := yyS[yypt-1].item.(*ident)
			if !ok {
				x.err("expected identifier or qualified identifier")
				return 1
			}

			var err error
			var agg bool
			if yyVAL.item, agg, err = newCall(f.s, yyS[yypt-0].item.([]expression)); err != nil {
				x.err("%v", err)
				return 1
			}
			if n := len(x.agg); n > 0 {
				x.agg[n-1] = x.agg[n-1] || agg
			}
		}
	case 94:
		yyVAL.item = yyS[yypt-0].item
	case 95:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation('^', yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 96:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation('|', yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 97:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation('-', yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 98:

		{
			var err error
			yyVAL.item, err = newBinaryOperation('+', yyS[yypt-2].item, yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 99:
		yyVAL.item = yyS[yypt-0].item
	case 100:

		{
			var err error
			yyVAL.item, err = newBinaryOperation(andnot, yyS[yypt-2].item, yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 101:

		{
			var err error
			yyVAL.item, err = newBinaryOperation('&', yyS[yypt-2].item, yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 102:

		{
			var err error
			yyVAL.item, err = newBinaryOperation(lsh, yyS[yypt-2].item, yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 103:

		{
			var err error
			yyVAL.item, err = newBinaryOperation(rsh, yyS[yypt-2].item, yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 104:

		{
			var err error
			yyVAL.item, err = newBinaryOperation('%', yyS[yypt-2].item, yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 105:

		{
			var err error
			yyVAL.item, err = newBinaryOperation('/', yyS[yypt-2].item, yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 106:

		{
			var err error
			yyVAL.item, err = newBinaryOperation('*', yyS[yypt-2].item, yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 107:
		yyVAL.item = yyS[yypt-0].item
	case 108:

		{
			yyVAL.item = fmt.Sprintf("%s.%s", yyS[yypt-2].item.(string), yyS[yypt-0].item.(string))
		}
	case 109:

		{
			yyVAL.item = []interface{}{yyS[yypt-1].item, yyS[yypt-0].item}
		}
	case 110:
		yyVAL.item = yyS[yypt-0].item
	case 111:

		{
			yyVAL.item = yyS[yypt-2].item
		}
	case 114:

		{
			yyVAL.item = ""
		}
	case 115:

		{
			yyVAL.item = yyS[yypt-0].item
		}
	case 116:

		{
			yyVAL.list = []interface{}{yyS[yypt-0].item}
		}
	case 117:

		{
			yyVAL.list = append(yyS[yypt-2].list, yyS[yypt-0].item)
		}
	case 118:

		{
			yyVAL.item = rollbackStmt{}
		}
	case 119:

		{
			x := yylex.(*lexer)
			n := len(x.agg)
			yyVAL.item = &selectStmt{
				distinct:      yyS[yypt-8].item.(bool),
				flds:          yyS[yypt-7].item.([]*fld),
				from:          &crossJoinRset{sources: yyS[yypt-5].list},
				hasAggregates: x.agg[n-1],
				where:         yyS[yypt-4].item.(*whereRset),
				group:         yyS[yypt-3].item.(*groupByRset),
				order:         yyS[yypt-2].item.(*orderByRset),
				limit:         yyS[yypt-1].item.(*limitRset),
				offset:        yyS[yypt-0].item.(*offsetRset),
			}
			x.agg = x.agg[:n-1]
		}
	case 120:

		{
			x := yylex.(*lexer)
			n := len(x.agg)
			yyVAL.item = &selectStmt{
				distinct:      yyS[yypt-9].item.(bool),
				flds:          yyS[yypt-8].item.([]*fld),
				from:          &crossJoinRset{sources: yyS[yypt-6].list},
				hasAggregates: x.agg[n-1],
				where:         yyS[yypt-4].item.(*whereRset),
				group:         yyS[yypt-3].item.(*groupByRset),
				order:         yyS[yypt-2].item.(*orderByRset),
				limit:         yyS[yypt-1].item.(*limitRset),
				offset:        yyS[yypt-0].item.(*offsetRset),
			}
			x.agg = x.agg[:n-1]
		}
	case 121:

		{
			yyVAL.item = (*limitRset)(nil)
		}
	case 122:

		{
			yyVAL.item = &limitRset{expr: yyS[yypt-0].item.(expression)}
		}
	case 123:

		{
			yyVAL.item = (*offsetRset)(nil)
		}
	case 124:

		{
			yyVAL.item = &offsetRset{expr: yyS[yypt-0].item.(expression)}
		}
	case 125:

		{
			yyVAL.item = false
		}
	case 126:

		{
			yyVAL.item = true
		}
	case 127:

		{
			yyVAL.item = []*fld{}
		}
	case 128:

		{
			yyVAL.item = yyS[yypt-0].item
		}
	case 129:

		{
			yyVAL.item = yyS[yypt-1].item
		}
	case 130:

		{
			yyVAL.item = (*whereRset)(nil)
		}
	case 131:
		yyVAL.item = yyS[yypt-0].item
	case 132:

		{
			yyVAL.item = (*groupByRset)(nil)
		}
	case 133:
		yyVAL.item = yyS[yypt-0].item
	case 134:

		{
			yyVAL.item = (*orderByRset)(nil)
		}
	case 135:
		yyVAL.item = yyS[yypt-0].item
	case 136:

		{
			yyVAL.item = [2]*expression{nil, nil}
		}
	case 137:

		{
			hi := yyS[yypt-1].item.(expression)
			yyVAL.item = [2]*expression{nil, &hi}
		}
	case 138:

		{
			lo := yyS[yypt-2].item.(expression)
			yyVAL.item = [2]*expression{&lo, nil}
		}
	case 139:

		{
			lo := yyS[yypt-3].item.(expression)
			hi := yyS[yypt-1].item.(expression)
			yyVAL.item = [2]*expression{&lo, &hi}
		}
	case 140:
		yyVAL.item = yyS[yypt-0].item
	case 141:
		yyVAL.item = yyS[yypt-0].item
	case 142:
		yyVAL.item = yyS[yypt-0].item
	case 143:
		yyVAL.item = yyS[yypt-0].item
	case 144:
		yyVAL.item = yyS[yypt-0].item
	case 145:
		yyVAL.item = yyS[yypt-0].item
	case 146:
		yyVAL.item = yyS[yypt-0].item
	case 147:
		yyVAL.item = yyS[yypt-0].item
	case 148:
		yyVAL.item = yyS[yypt-0].item
	case 149:
		yyVAL.item = yyS[yypt-0].item
	case 150:
		yyVAL.item = yyS[yypt-0].item
	case 151:
		yyVAL.item = yyS[yypt-0].item
	case 152:
		yyVAL.item = yyS[yypt-0].item
	case 153:
		yyVAL.item = yyS[yypt-0].item
	case 154:

		{
			if yyS[yypt-0].item != nil {
				yylex.(*lexer).list = []stmt{yyS[yypt-0].item.(stmt)}
			}
		}
	case 155:

		{
			if yyS[yypt-0].item != nil {
				yylex.(*lexer).list = append(yylex.(*lexer).list, yyS[yypt-0].item.(stmt))
			}
		}
	case 156:
		yyVAL.item = yyS[yypt-0].item
	case 157:
		yyVAL.item = yyS[yypt-0].item
	case 158:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation(andand, yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 159:

		{
			yyVAL.item = &truncateTableStmt{tableName: yyS[yypt-0].item.(string)}
		}
	case 160:
		yyVAL.item = yyS[yypt-0].item
	case 161:
		yyVAL.item = yyS[yypt-0].item
	case 162:
		yyVAL.item = yyS[yypt-0].item
	case 163:
		yyVAL.item = yyS[yypt-0].item
	case 164:
		yyVAL.item = yyS[yypt-0].item
	case 165:
		yyVAL.item = yyS[yypt-0].item
	case 166:
		yyVAL.item = yyS[yypt-0].item
	case 167:
		yyVAL.item = yyS[yypt-0].item
	case 168:
		yyVAL.item = yyS[yypt-0].item
	case 169:
		yyVAL.item = yyS[yypt-0].item
	case 170:
		yyVAL.item = yyS[yypt-0].item
	case 171:
		yyVAL.item = yyS[yypt-0].item
	case 172:
		yyVAL.item = yyS[yypt-0].item
	case 173:
		yyVAL.item = yyS[yypt-0].item
	case 174:
		yyVAL.item = yyS[yypt-0].item
	case 175:
		yyVAL.item = yyS[yypt-0].item
	case 176:
		yyVAL.item = yyS[yypt-0].item
	case 177:
		yyVAL.item = yyS[yypt-0].item
	case 178:
		yyVAL.item = yyS[yypt-0].item
	case 179:
		yyVAL.item = yyS[yypt-0].item
	case 180:
		yyVAL.item = yyS[yypt-0].item
	case 181:
		yyVAL.item = yyS[yypt-0].item
	case 182:
		yyVAL.item = yyS[yypt-0].item
	case 183:
		yyVAL.item = yyS[yypt-0].item
	case 184:

		{
			yyVAL.item = &updateStmt{tableName: yyS[yypt-2].item.(string), list: yyS[yypt-1].item.([]assignment), where: yyS[yypt-0].item.(*whereRset).expr}
		}
	case 185:

		{
			yyVAL.item = nowhere
		}
	case 186:
		yyVAL.item = yyS[yypt-0].item
	case 187:
		yyVAL.item = yyS[yypt-0].item
	case 188:

		{
			var err error
			yyVAL.item, err = newUnaryOperation('^', yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 189:

		{
			var err error
			yyVAL.item, err = newUnaryOperation('!', yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 190:

		{
			var err error
			yyVAL.item, err = newUnaryOperation('-', yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 191:

		{
			var err error
			yyVAL.item, err = newUnaryOperation('+', yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				return 1
			}
		}
	case 192:

		{
			yyVAL.item = &whereRset{expr: yyS[yypt-0].item.(expression)}
		}
	}
	goto yystack /* stack new state and value */
}
