// Copyright (c) 2013 Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Inital yacc source generated by ebnf2y[1]
// at 2013-10-04 23:10:47.861401015 +0200 CEST
//
//  $ ebnf2y -o ql.y -oe ql.ebnf -start StatementList -pkg ql -p _
//
// CAUTION: If this file is a Go source file (*.go), it was generated
// automatically by '$ go tool yacc' from a *.y file - DO NOT EDIT in that case!
//
//   [1]: http://github.com/cznic/ebnf2y

package ql

import __yyfmt__ "fmt"

import (
	"fmt"
)

type yySymType struct {
	yys  int
	line int
	col  int
	item interface{}
	list []interface{}
}

const add = 57346
const alter = 57347
const and = 57348
const andand = 57349
const andnot = 57350
const as = 57351
const asc = 57352
const begin = 57353
const between = 57354
const bigIntType = 57355
const bigRatType = 57356
const blobType = 57357
const boolType = 57358
const by = 57359
const byteType = 57360
const column = 57361
const commit = 57362
const complex128Type = 57363
const complex64Type = 57364
const create = 57365
const deleteKwd = 57366
const desc = 57367
const distinct = 57368
const drop = 57369
const eq = 57370
const falseKwd = 57371
const floatType = 57372
const float32Type = 57373
const float64Type = 57374
const floatLit = 57375
const from = 57376
const ge = 57377
const group = 57378
const identifier = 57379
const imaginaryLit = 57380
const in = 57381
const insert = 57382
const intType = 57383
const int16Type = 57384
const int32Type = 57385
const int64Type = 57386
const int8Type = 57387
const is = 57388
const into = 57389
const intLit = 57390
const le = 57391
const lsh = 57392
const neq = 57393
const not = 57394
const null = 57395
const order = 57396
const oror = 57397
const qlParam = 57398
const rollback = 57399
const rsh = 57400
const runeType = 57401
const selectKwd = 57402
const stringType = 57403
const stringLit = 57404
const tableKwd = 57405
const transaction = 57406
const trueKwd = 57407
const truncate = 57408
const uintType = 57409
const uint16Type = 57410
const uint32Type = 57411
const uint64Type = 57412
const uint8Type = 57413
const update = 57414
const values = 57415
const where = 57416

var yyToknames = []string{
	"add",
	"alter",
	"and",
	"andand",
	"andnot",
	"as",
	"asc",
	"begin",
	"between",
	"bigIntType",
	"bigRatType",
	"blobType",
	"boolType",
	"by",
	"byteType",
	"column",
	"commit",
	"complex128Type",
	"complex64Type",
	"create",
	"deleteKwd",
	"desc",
	"distinct",
	"drop",
	"eq",
	"falseKwd",
	"floatType",
	"float32Type",
	"float64Type",
	"floatLit",
	"from",
	"ge",
	"group",
	"identifier",
	"imaginaryLit",
	"in",
	"insert",
	"intType",
	"int16Type",
	"int32Type",
	"int64Type",
	"int8Type",
	"is",
	"into",
	"intLit",
	"le",
	"lsh",
	"neq",
	"not",
	"null",
	"order",
	"oror",
	"qlParam",
	"rollback",
	"rsh",
	"runeType",
	"selectKwd",
	"stringType",
	"stringLit",
	"tableKwd",
	"transaction",
	"trueKwd",
	"truncate",
	"uintType",
	"uint16Type",
	"uint32Type",
	"uint64Type",
	"uint8Type",
	"update",
	"values",
	"where",
}
var yyStatenames = []string{}

const yyEOFCode = 1
const yyErrCode = 2
const yyMaxDepth = 200

var yyExca = []int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyNprod = 178
const yyPrivate = 57344

var yyTokenNames []string
var yyStates []string

const yyLast = 707

var yyAct = []int{

	196, 153, 197, 159, 256, 236, 52, 152, 211, 162,
	99, 12, 66, 49, 241, 212, 26, 53, 50, 147,
	129, 47, 111, 75, 76, 77, 78, 54, 79, 111,
	277, 80, 81, 140, 111, 261, 48, 139, 100, 67,
	82, 83, 84, 70, 111, 270, 260, 74, 71, 221,
	253, 85, 86, 87, 88, 89, 263, 105, 72, 244,
	222, 248, 131, 68, 251, 242, 63, 227, 145, 90,
	132, 91, 73, 219, 111, 69, 225, 92, 93, 94,
	95, 96, 125, 126, 127, 128, 208, 65, 272, 106,
	217, 210, 246, 56, 164, 58, 59, 198, 207, 130,
	133, 134, 135, 170, 57, 146, 108, 104, 250, 156,
	160, 233, 155, 48, 149, 230, 202, 110, 151, 158,
	106, 35, 23, 28, 173, 167, 176, 177, 178, 179,
	180, 181, 166, 169, 165, 157, 125, 126, 127, 128,
	31, 164, 193, 182, 183, 184, 185, 29, 27, 199,
	125, 126, 127, 128, 203, 23, 205, 186, 187, 188,
	189, 190, 191, 192, 55, 111, 204, 258, 113, 175,
	174, 216, 117, 220, 32, 172, 101, 215, 106, 218,
	239, 165, 200, 168, 37, 238, 109, 30, 124, 2,
	274, 34, 102, 154, 267, 119, 259, 224, 214, 115,
	36, 114, 171, 240, 100, 275, 118, 269, 231, 121,
	249, 123, 116, 228, 111, 103, 38, 229, 243, 235,
	234, 141, 142, 143, 144, 247, 245, 232, 39, 201,
	40, 41, 42, 43, 161, 254, 97, 148, 252, 120,
	122, 255, 14, 13, 1, 137, 44, 33, 11, 213,
	163, 262, 64, 264, 273, 257, 60, 62, 265, 107,
	266, 160, 10, 268, 136, 237, 46, 112, 271, 75,
	76, 77, 78, 276, 79, 51, 226, 80, 81, 3,
	9, 8, 206, 7, 61, 67, 82, 83, 84, 70,
	6, 209, 195, 74, 71, 138, 5, 85, 86, 87,
	88, 89, 150, 98, 72, 4, 0, 0, 0, 68,
	0, 0, 63, 0, 0, 90, 0, 91, 73, 0,
	0, 69, 0, 92, 93, 94, 95, 96, 0, 0,
	0, 0, 0, 65, 0, 0, 0, 0, 223, 56,
	0, 58, 59, 75, 76, 77, 78, 0, 79, 0,
	57, 80, 81, 0, 0, 0, 0, 0, 0, 67,
	82, 83, 84, 70, 0, 0, 0, 74, 71, 0,
	0, 85, 86, 87, 88, 89, 0, 0, 72, 0,
	0, 0, 0, 68, 0, 0, 63, 0, 0, 90,
	0, 91, 73, 0, 0, 69, 0, 92, 93, 94,
	95, 96, 0, 0, 0, 0, 0, 65, 0, 75,
	76, 77, 78, 56, 79, 58, 59, 80, 81, 0,
	0, 0, 0, 194, 57, 67, 82, 83, 84, 70,
	0, 0, 0, 74, 71, 0, 0, 85, 86, 87,
	88, 89, 0, 0, 72, 0, 0, 0, 0, 68,
	0, 0, 63, 0, 0, 90, 0, 91, 73, 0,
	0, 69, 0, 92, 93, 94, 95, 96, 0, 0,
	0, 0, 0, 65, 0, 75, 76, 77, 78, 56,
	79, 58, 59, 80, 81, 0, 45, 0, 0, 0,
	57, 67, 82, 83, 84, 70, 0, 0, 0, 74,
	71, 0, 0, 85, 86, 87, 88, 89, 0, 0,
	72, 0, 0, 0, 0, 68, 0, 0, 63, 0,
	0, 90, 0, 91, 73, 0, 0, 69, 0, 92,
	93, 94, 95, 96, 0, 75, 76, 77, 78, 65,
	79, 0, 0, 80, 81, 56, 0, 58, 59, 0,
	0, 67, 82, 83, 84, 70, 57, 0, 0, 74,
	71, 0, 0, 85, 86, 87, 88, 89, 0, 0,
	72, 0, 0, 0, 0, 68, 0, 0, 63, 0,
	0, 90, 0, 91, 73, 0, 0, 69, 0, 92,
	93, 94, 95, 96, 0, 75, 76, 77, 78, 65,
	79, 0, 0, 80, 81, 0, 0, 0, 0, 0,
	0, 0, 82, 83, 84, 0, 0, 0, 0, 0,
	0, 0, 0, 85, 86, 87, 88, 89, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 15,
	0, 90, 0, 91, 0, 16, 0, 0, 0, 92,
	93, 94, 95, 96, 17, 0, 0, 18, 19, 0,
	0, 20, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 21, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 22, 0, 0, 23, 0, 0, 0, 0, 0,
	24, 0, 0, 0, 0, 0, 25,
}
var yyPact = []int{

	634, -76, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 85, 59, -1000, 84, 153,
	77, 127, -1000, 165, 58, 147, 634, 147, -1000, 147,
	147, 147, 147, 396, -1000, 147, 139, -1000, -1000, 188,
	30, 46, -1000, 29, 152, -1000, 41, -1000, 159, 194,
	-1000, 160, -1, 12, -1000, -44, 522, 522, 522, 522,
	-1000, -1000, -1000, -1000, -1000, 462, 28, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -72, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 46, -1000,
	43, -1000, 139, 174, 139, -1000, 462, 62, 139, 57,
	462, 462, -1000, 146, 462, 26, 163, 462, 117, 462,
	462, 462, 462, 462, 462, 462, 462, 462, 462, 462,
	462, 462, 462, 462, 462, 462, -1000, -1000, -1000, 330,
	462, -44, -44, -44, -44, 19, 462, 145, -1000, -1000,
	40, 462, -1000, 582, 139, -1000, 110, 21, -1000, 8,
	-1000, 15, -1000, 189, -1000, 95, -1000, 194, -1000, -1000,
	462, 13, 462, 67, -1000, 120, -1, -1, -1, -1,
	-1, -1, 12, 12, 12, 12, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -33, 256, -2, -1000, 110, -1000, -11,
	-1000, -1000, 139, 110, -1000, -1000, 39, 462, -1000, 35,
	104, 149, -1000, -1000, 143, -78, -13, 462, 53, 462,
	-1000, -1000, 10, -1000, -21, -1000, 32, -1000, -1000, -14,
	139, -28, -1000, 139, -1000, 149, 113, -1000, 179, -1000,
	-32, -1000, -1000, -43, 462, -1, -1000, -26, -1000, -1000,
	462, -1000, -1000, -1000, -1000, 113, -1000, -1000, 177, 139,
	-1000, -1000, -1, -1000, 110, -31, -1000, 462, -1000, -1000,
	11, 180, 462, -1000, -1000, -1000, -48, -1000,
}
var yyPgo = []int{

	0, 305, 10, 303, 302, 296, 295, 292, 7, 1,
	3, 291, 290, 284, 283, 282, 281, 280, 279, 2,
	0, 276, 18, 275, 21, 267, 266, 265, 264, 262,
	259, 258, 257, 256, 255, 254, 252, 164, 6, 17,
	9, 250, 249, 248, 11, 247, 246, 8, 5, 4,
	245, 189, 244, 200, 13, 243, 12, 27, 242, 237,
	15, 234, 229, 227, 217, 210, 207, 203,
}
var yyR1 = []int{

	0, 1, 1, 2, 3, 4, 4, 62, 62, 5,
	6, 7, 7, 8, 9, 10, 11, 11, 63, 63,
	12, 13, 14, 15, 15, 64, 64, 16, 16, 17,
	18, 19, 19, 20, 21, 21, 65, 65, 22, 22,
	22, 22, 22, 22, 22, 23, 23, 23, 23, 23,
	23, 23, 24, 25, 25, 26, 26, 27, 28, 29,
	29, 30, 30, 31, 31, 66, 66, 32, 32, 32,
	32, 32, 32, 32, 33, 33, 33, 33, 34, 35,
	35, 35, 37, 37, 37, 37, 37, 38, 38, 38,
	38, 38, 39, 39, 39, 39, 39, 39, 39, 39,
	36, 36, 40, 41, 41, 67, 67, 42, 42, 61,
	61, 43, 44, 44, 45, 45, 46, 46, 46, 47,
	47, 48, 48, 49, 49, 50, 50, 50, 50, 51,
	51, 51, 51, 51, 51, 51, 51, 51, 51, 51,
	51, 52, 52, 53, 54, 54, 55, 56, 56, 56,
	56, 56, 56, 56, 56, 56, 56, 56, 56, 56,
	56, 56, 56, 56, 56, 56, 56, 56, 56, 58,
	59, 59, 57, 57, 57, 57, 57, 60,
}
var yyR2 = []int{

	0, 5, 6, 3, 3, 0, 3, 0, 1, 2,
	3, 0, 1, 2, 1, 3, 0, 3, 0, 1,
	1, 4, 8, 0, 3, 0, 1, 3, 4, 3,
	0, 1, 3, 3, 0, 3, 0, 1, 1, 5,
	6, 5, 6, 3, 4, 1, 3, 3, 3, 3,
	3, 3, 2, 0, 2, 1, 3, 3, 3, 10,
	5, 0, 3, 0, 5, 0, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 3, 4, 0,
	1, 1, 1, 1, 2, 2, 2, 1, 3, 3,
	3, 3, 1, 3, 3, 3, 3, 3, 3, 3,
	1, 3, 2, 1, 4, 0, 1, 0, 2, 1,
	3, 1, 8, 9, 0, 1, 1, 1, 2, 0,
	1, 0, 1, 0, 1, 3, 4, 4, 5, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 3, 1, 1, 3, 3, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 4,
	0, 1, 1, 2, 2, 2, 2, 2,
}
var yyChk = []int{

	-1000, -52, -51, -18, -1, -5, -12, -14, -16, -17,
	-29, -43, -44, -55, -58, 5, 11, 20, 23, 24,
	27, 40, 57, 60, 66, 72, 92, 63, 64, 63,
	34, 63, 47, -45, 26, 63, -53, 37, -51, -53,
	-53, -53, -53, -53, -46, 90, -26, -24, -19, -54,
	-22, -23, -38, -39, -57, -37, 83, 94, 85, 86,
	-33, -13, -32, 56, -36, 77, -56, 29, 53, 65,
	33, 38, 48, 62, 37, 13, 14, 15, 16, 18,
	21, 22, 30, 31, 32, 41, 42, 43, 44, 45,
	59, 61, 67, 68, 69, 70, 71, -53, -3, -2,
	-9, 37, 4, 27, 77, -60, 74, -30, 77, 34,
	76, 55, -25, 9, 7, 39, 52, 12, 46, 35,
	79, 49, 80, 51, 28, 83, 84, 85, 86, 8,
	87, 50, 58, 88, 89, 90, -28, -50, -6, 81,
	77, -37, -37, -37, -37, -19, 77, 91, -59, -60,
	-4, 75, -8, -9, 19, -8, -19, 73, -44, -10,
	-9, -61, -40, -41, 37, 77, -24, -54, 37, -22,
	77, 39, 12, -38, 53, 52, -38, -38, -38, -38,
	-38, -38, -39, -39, -39, -39, -57, -57, -57, -57,
	-57, -57, -57, -19, 93, -7, -20, -19, 78, -19,
	37, -62, 76, -19, -56, -9, -15, 77, 78, -11,
	76, -47, -60, -42, 9, -44, -20, 77, -38, 6,
	53, 82, 93, 82, -19, 78, -21, 78, -2, -64,
	76, -20, -63, 76, -40, -47, -48, -27, 36, 37,
	-67, 92, 78, -20, 6, -38, 82, -19, 82, -65,
	76, 78, -8, 78, -9, -48, -49, -34, 54, 17,
	78, 78, -38, 82, -19, -31, -49, 17, -10, -66,
	76, -20, 77, -35, 10, 25, -20, 78,
}
var yyDef = []int{

	30, -2, 141, 129, 130, 131, 132, 133, 134, 135,
	136, 137, 138, 139, 140, 0, 0, 20, 0, 0,
	0, 0, 111, 114, 0, 0, 30, 0, 9, 0,
	0, 0, 0, 0, 115, 0, 0, 143, 142, 0,
	0, 27, 29, 61, 0, 116, 117, 55, 53, 31,
	144, 38, 45, 87, 92, 172, 0, 0, 0, 0,
	82, 83, 74, 75, 76, 0, 0, 67, 68, 69,
	70, 71, 72, 73, 100, 147, 148, 149, 150, 151,
	152, 153, 154, 155, 156, 157, 158, 159, 160, 161,
	162, 163, 164, 165, 166, 167, 168, 146, 170, 5,
	0, 14, 0, 0, 0, 28, 0, 0, 0, 0,
	118, 0, 52, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 84, 85, 86, 0,
	11, 173, 174, 175, 176, 0, 0, 0, 169, 171,
	7, 0, 1, 0, 0, 23, 177, 0, 60, 0,
	16, 119, 109, 107, 103, 0, 56, 32, 54, 145,
	0, 0, 0, 0, 43, 0, 46, 47, 48, 49,
	50, 51, 88, 89, 90, 91, 93, 94, 95, 96,
	97, 98, 99, 0, 0, 0, 12, 34, 77, 0,
	101, 4, 8, 3, 13, 2, 25, 0, 62, 18,
	119, 121, 120, 102, 0, 105, 0, 0, 0, 0,
	44, 58, 0, 125, 0, 10, 36, 21, 6, 0,
	26, 0, 15, 19, 110, 121, 123, 122, 0, 108,
	0, 106, 39, 0, 0, 41, 127, 0, 126, 33,
	37, 22, 24, 63, 17, 123, 112, 124, 0, 0,
	104, 40, 42, 128, 35, 65, 113, 0, 57, 59,
	66, 79, 0, 78, 80, 81, 0, 64,
}
var yyTok1 = []int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 94, 3, 3, 3, 88, 87, 3,
	77, 78, 90, 86, 76, 85, 91, 89, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 93, 92,
	80, 75, 79, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 81, 3, 82, 83, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 84,
}
var yyTok2 = []int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74,
}
var yyTok3 = []int{
	0,
}

/*	parser for yacc output	*/

var yyDebug = 0

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

const yyFlag = -1000

func yyTokname(c int) string {
	// 4 is TOKSTART above
	if c >= 4 && c-4 < len(yyToknames) {
		if yyToknames[c-4] != "" {
			return yyToknames[c-4]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yylex1(lex yyLexer, lval *yySymType) int {
	c := 0
	char := lex.Lex(lval)
	if char <= 0 {
		c = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		c = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			c = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		c = yyTok3[i+0]
		if c == char {
			c = yyTok3[i+1]
			goto out
		}
	}

out:
	if c == 0 {
		c = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(c), uint(char))
	}
	return c
}

func yyParse(yylex yyLexer) int {
	var yyn int
	var yylval yySymType
	var yyVAL yySymType
	yyS := make([]yySymType, yyMaxDepth)

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yychar := -1
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yychar), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yychar < 0 {
		yychar = yylex1(yylex, &yylval)
	}
	yyn += yychar
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yychar { /* valid shift */
		yychar = -1
		yyVAL = yylval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yychar < 0 {
			yychar = yylex1(yylex, &yylval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yychar {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error("syntax error")
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yychar))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yychar))
			}
			if yychar == yyEOFCode {
				goto ret1
			}
			yychar = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 1:

		{
			yyVAL.item = &alterTableAddStmt{tableName: yyS[yypt-2].item.(string), c: yyS[yypt-0].item.(*col)}
		}
	case 2:

		{
			yyVAL.item = &alterTableDropColumnStmt{tableName: yyS[yypt-3].item.(string), colName: yyS[yypt-0].item.(string)}
		}
	case 3:

		{
			yyVAL.item = assignment{colName: yyS[yypt-2].item.(string), expr: yyS[yypt-0].item.(expression)}
		}
	case 4:

		{
			yyVAL.item = append([]assignment{yyS[yypt-2].item.(assignment)}, yyS[yypt-1].item.([]assignment)...)
		}
	case 5:

		{
			yyVAL.item = []assignment{}
		}
	case 6:

		{
			yyVAL.item = append(yyS[yypt-2].item.([]assignment), yyS[yypt-0].item.(assignment))
		}
	case 9:

		{
			yyVAL.item = beginTransactionStmt{}
		}
	case 10:

		{
			yyVAL.item = yyS[yypt-1].item
		}
	case 11:

		{
			yyVAL.item = []expression{}
		}
	case 12:
		yyVAL.item = yyS[yypt-0].item
	case 13:

		{
			yyVAL.item = &col{name: yyS[yypt-1].item.(string), typ: yyS[yypt-0].item.(int)}
		}
	case 14:
		yyVAL.item = yyS[yypt-0].item
	case 15:

		{
			yyVAL.item = append([]string{yyS[yypt-2].item.(string)}, yyS[yypt-1].item.([]string)...)
		}
	case 16:

		{
			yyVAL.item = []string{}
		}
	case 17:

		{
			yyVAL.item = append(yyS[yypt-2].item.([]string), yyS[yypt-0].item.(string))
		}
	case 20:

		{
			yyVAL.item = commitStmt{}
		}
	case 21:

		{
			yyVAL.item = &conversion{typ: yyS[yypt-3].item.(int), val: yyS[yypt-1].item.(expression)}
		}
	case 22:

		{
			yyVAL.item = &createTableStmt{tableName: yyS[yypt-5].item.(string), cols: append([]*col{yyS[yypt-3].item.(*col)}, yyS[yypt-2].item.([]*col)...)}
		}
	case 23:

		{
			yyVAL.item = []*col{}
		}
	case 24:

		{
			yyVAL.item = append(yyS[yypt-2].item.([]*col), yyS[yypt-0].item.(*col))
		}
	case 27:

		{
			yyVAL.item = &truncateTableStmt{yyS[yypt-0].item.(string)}
		}
	case 28:

		{
			yyVAL.item = &deleteStmt{tableName: yyS[yypt-1].item.(string), where: yyS[yypt-0].item.(*whereRset).expr}
		}
	case 29:

		{
			yyVAL.item = &dropTableStmt{tableName: yyS[yypt-0].item.(string)}
		}
	case 30:

		{
			yyVAL.item = nil
		}
	case 31:
		yyVAL.item = yyS[yypt-0].item
	case 32:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation(oror, yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 33:

		{
			yyVAL.item = append([]expression{yyS[yypt-2].item.(expression)}, yyS[yypt-1].item.([]expression)...)
		}
	case 34:

		{
			yyVAL.item = []expression(nil)
		}
	case 35:

		{
			yyVAL.item = append(yyS[yypt-2].item.([]expression), yyS[yypt-0].item.(expression))
		}
	case 38:
		yyVAL.item = yyS[yypt-0].item
	case 39:

		{
			yyVAL.item = &pIn{expr: yyS[yypt-4].item.(expression), list: yyS[yypt-1].item.([]expression)}
		}
	case 40:

		{
			yyVAL.item = &pIn{expr: yyS[yypt-5].item.(expression), not: true, list: yyS[yypt-1].item.([]expression)}
		}
	case 41:

		{
			yyVAL.item = &pBetween{expr: yyS[yypt-4].item.(expression), l: yyS[yypt-2].item.(expression), h: yyS[yypt-0].item.(expression)}
		}
	case 42:

		{
			yyVAL.item = &pBetween{expr: yyS[yypt-5].item.(expression), not: true, l: yyS[yypt-2].item.(expression), h: yyS[yypt-0].item.(expression)}
		}
	case 43:

		{
			yyVAL.item = &isNull{expr: yyS[yypt-2].item.(expression)}
		}
	case 44:

		{
			yyVAL.item = &isNull{expr: yyS[yypt-3].item.(expression), not: true}
		}
	case 45:
		yyVAL.item = yyS[yypt-0].item
	case 46:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation(ge, yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 47:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation('>', yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 48:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation(le, yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 49:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation('<', yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 50:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation(neq, yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 51:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation(eq, yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 52:

		{
			expr, name := yyS[yypt-1].item.(expression), yyS[yypt-0].item.(string)
			if name == "" {
				s, ok := expr.(*ident)
				if ok {
					name = s.s
				}
			}
			yyVAL.item = &fld{expr: expr, name: name}
		}
	case 53:

		{
			yyVAL.item = ""
		}
	case 54:

		{
			yyVAL.item = yyS[yypt-0].item
		}
	case 55:

		{
			yyVAL.item = []*fld{yyS[yypt-0].item.(*fld)}
		}
	case 56:

		{
			l, f := yyS[yypt-2].item.([]*fld), yyS[yypt-0].item.(*fld)
			if f.name != "" {
				if f := findFld(l, f.name); f != nil {
					yylex.(*lexer).err("duplicate field name %q", f.name)
					goto ret1
				}
			}

			yyVAL.item = append(yyS[yypt-2].item.([]*fld), yyS[yypt-0].item.(*fld))
		}
	case 57:

		{
			yyVAL.item = &groupByRset{colNames: yyS[yypt-0].item.([]string)}
		}
	case 58:

		{
			yyVAL.item = yyS[yypt-1].item
		}
	case 59:

		{
			yyVAL.item = &insertIntoStmt{tableName: yyS[yypt-7].item.(string), colNames: yyS[yypt-6].item.([]string), lists: append([][]expression{yyS[yypt-3].item.([]expression)}, yyS[yypt-1].item.([][]expression)...)}
		}
	case 60:

		{
			yyVAL.item = &insertIntoStmt{tableName: yyS[yypt-2].item.(string), colNames: yyS[yypt-1].item.([]string), sel: yyS[yypt-0].item.(*selectStmt)}
		}
	case 61:

		{
			yyVAL.item = []string{}
		}
	case 62:

		{
			yyVAL.item = yyS[yypt-1].item
		}
	case 63:

		{
			yyVAL.item = [][]expression{}
		}
	case 64:

		{
			yyVAL.item = append(yyS[yypt-4].item.([][]expression), yyS[yypt-1].item.([]expression))
		}
	case 67:
		yyVAL.item = yyS[yypt-0].item
	case 68:
		yyVAL.item = yyS[yypt-0].item
	case 69:
		yyVAL.item = yyS[yypt-0].item
	case 70:
		yyVAL.item = yyS[yypt-0].item
	case 71:
		yyVAL.item = yyS[yypt-0].item
	case 72:
		yyVAL.item = yyS[yypt-0].item
	case 73:
		yyVAL.item = yyS[yypt-0].item
	case 74:

		{
			yyVAL.item = value{yyS[yypt-0].item}
		}
	case 75:

		{
			yyVAL.item = parameter{yyS[yypt-0].item.(int)}
		}
	case 76:

		{
			yyVAL.item = &ident{yyS[yypt-0].item.(string)}
		}
	case 77:

		{
			yyVAL.item = &pexpr{expr: yyS[yypt-1].item.(expression)}
		}
	case 78:

		{
			yyVAL.item = &orderByRset{by: yyS[yypt-1].item.([]expression), asc: yyS[yypt-0].item.(bool)}
		}
	case 79:

		{
			yyVAL.item = true // ASC by default
		}
	case 80:

		{
			yyVAL.item = true
		}
	case 81:

		{
			yyVAL.item = false
		}
	case 82:
		yyVAL.item = yyS[yypt-0].item
	case 83:
		yyVAL.item = yyS[yypt-0].item
	case 84:

		{
			var err error
			if yyVAL.item, err = newIndex(yyS[yypt-1].item.(expression), yyS[yypt-0].item.(expression)); err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 85:

		{
			var err error
			s := yyS[yypt-0].item.([2]*expression)
			if yyVAL.item, err = newSlice(yyS[yypt-1].item.(expression), s[0], s[1]); err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 86:

		{
			x := yylex.(*lexer)
			f, ok := yyS[yypt-1].item.(*ident)
			if !ok {
				x.err("expected identifier or qualified identifier")
				goto ret1
			}

			var err error
			var agg bool
			if yyVAL.item, agg, err = newCall(f.s, yyS[yypt-0].item.([]expression)); err != nil {
				x.err("%v", err)
				goto ret1
			}
			if n := len(x.agg); n > 0 {
				x.agg[n-1] = x.agg[n-1] || agg
			}
		}
	case 87:
		yyVAL.item = yyS[yypt-0].item
	case 88:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation('^', yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 89:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation('|', yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 90:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation('-', yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 91:

		{
			var err error
			yyVAL.item, err = newBinaryOperation('+', yyS[yypt-2].item, yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 92:
		yyVAL.item = yyS[yypt-0].item
	case 93:

		{
			var err error
			yyVAL.item, err = newBinaryOperation(andnot, yyS[yypt-2].item, yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 94:

		{
			var err error
			yyVAL.item, err = newBinaryOperation('&', yyS[yypt-2].item, yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 95:

		{
			var err error
			yyVAL.item, err = newBinaryOperation(lsh, yyS[yypt-2].item, yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 96:

		{
			var err error
			yyVAL.item, err = newBinaryOperation(rsh, yyS[yypt-2].item, yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 97:

		{
			var err error
			yyVAL.item, err = newBinaryOperation('%', yyS[yypt-2].item, yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 98:

		{
			var err error
			yyVAL.item, err = newBinaryOperation('/', yyS[yypt-2].item, yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 99:

		{
			var err error
			yyVAL.item, err = newBinaryOperation('*', yyS[yypt-2].item, yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 100:
		yyVAL.item = yyS[yypt-0].item
	case 101:

		{
			yyVAL.item = fmt.Sprintf("%s.%s", yyS[yypt-2].item.(string), yyS[yypt-0].item.(string))
		}
	case 102:

		{
			yyVAL.item = []interface{}{yyS[yypt-1].item, yyS[yypt-0].item}
		}
	case 103:
		yyVAL.item = yyS[yypt-0].item
	case 104:

		{
			yyVAL.item = yyS[yypt-2].item
		}
	case 107:

		{
			yyVAL.item = ""
		}
	case 108:

		{
			yyVAL.item = yyS[yypt-0].item
		}
	case 109:

		{
			yyVAL.list = []interface{}{yyS[yypt-0].item}
		}
	case 110:

		{
			yyVAL.list = append(yyS[yypt-2].list, yyS[yypt-0].item)
		}
	case 111:

		{
			yyVAL.item = rollbackStmt{}
		}
	case 112:

		{
			x := yylex.(*lexer)
			n := len(x.agg)
			yyVAL.item = &selectStmt{
				distinct:      yyS[yypt-6].item.(bool),
				flds:          yyS[yypt-5].item.([]*fld),
				from:          &crossJoinRset{sources: yyS[yypt-3].list},
				hasAggregates: x.agg[n-1],
				where:         yyS[yypt-2].item.(*whereRset),
				group:         yyS[yypt-1].item.(*groupByRset),
				order:         yyS[yypt-0].item.(*orderByRset),
			}
			x.agg = x.agg[:n-1]
		}
	case 113:

		{
			x := yylex.(*lexer)
			n := len(x.agg)
			yyVAL.item = &selectStmt{
				distinct:      yyS[yypt-7].item.(bool),
				flds:          yyS[yypt-6].item.([]*fld),
				from:          &crossJoinRset{sources: yyS[yypt-4].list},
				hasAggregates: x.agg[n-1],
				where:         yyS[yypt-2].item.(*whereRset),
				group:         yyS[yypt-1].item.(*groupByRset),
				order:         yyS[yypt-0].item.(*orderByRset),
			}
			x.agg = x.agg[:n-1]
		}
	case 114:

		{
			yyVAL.item = false
		}
	case 115:

		{
			yyVAL.item = true
		}
	case 116:

		{
			yyVAL.item = []*fld{}
		}
	case 117:

		{
			yyVAL.item = yyS[yypt-0].item
		}
	case 118:

		{
			yyVAL.item = yyS[yypt-1].item
		}
	case 119:

		{
			yyVAL.item = (*whereRset)(nil)
		}
	case 120:
		yyVAL.item = yyS[yypt-0].item
	case 121:

		{
			yyVAL.item = (*groupByRset)(nil)
		}
	case 122:
		yyVAL.item = yyS[yypt-0].item
	case 123:

		{
			yyVAL.item = (*orderByRset)(nil)
		}
	case 124:
		yyVAL.item = yyS[yypt-0].item
	case 125:

		{
			yyVAL.item = [2]*expression{nil, nil}
		}
	case 126:

		{
			hi := yyS[yypt-1].item.(expression)
			yyVAL.item = [2]*expression{nil, &hi}
		}
	case 127:

		{
			lo := yyS[yypt-2].item.(expression)
			yyVAL.item = [2]*expression{&lo, nil}
		}
	case 128:

		{
			lo := yyS[yypt-3].item.(expression)
			hi := yyS[yypt-1].item.(expression)
			yyVAL.item = [2]*expression{&lo, &hi}
		}
	case 129:
		yyVAL.item = yyS[yypt-0].item
	case 130:
		yyVAL.item = yyS[yypt-0].item
	case 131:
		yyVAL.item = yyS[yypt-0].item
	case 132:
		yyVAL.item = yyS[yypt-0].item
	case 133:
		yyVAL.item = yyS[yypt-0].item
	case 134:
		yyVAL.item = yyS[yypt-0].item
	case 135:
		yyVAL.item = yyS[yypt-0].item
	case 136:
		yyVAL.item = yyS[yypt-0].item
	case 137:
		yyVAL.item = yyS[yypt-0].item
	case 138:
		yyVAL.item = yyS[yypt-0].item
	case 139:
		yyVAL.item = yyS[yypt-0].item
	case 140:
		yyVAL.item = yyS[yypt-0].item
	case 141:

		{
			if yyS[yypt-0].item != nil {
				yylex.(*lexer).list = []stmt{yyS[yypt-0].item.(stmt)}
			}
		}
	case 142:

		{
			if yyS[yypt-0].item != nil {
				yylex.(*lexer).list = append(yylex.(*lexer).list, yyS[yypt-0].item.(stmt))
			}
		}
	case 143:
		yyVAL.item = yyS[yypt-0].item
	case 144:
		yyVAL.item = yyS[yypt-0].item
	case 145:

		{
			var err error
			if yyVAL.item, err = newBinaryOperation(andand, yyS[yypt-2].item, yyS[yypt-0].item); err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 146:

		{
			yyVAL.item = &truncateTableStmt{tableName: yyS[yypt-0].item.(string)}
		}
	case 147:
		yyVAL.item = yyS[yypt-0].item
	case 148:
		yyVAL.item = yyS[yypt-0].item
	case 149:
		yyVAL.item = yyS[yypt-0].item
	case 150:
		yyVAL.item = yyS[yypt-0].item
	case 151:
		yyVAL.item = yyS[yypt-0].item
	case 152:
		yyVAL.item = yyS[yypt-0].item
	case 153:
		yyVAL.item = yyS[yypt-0].item
	case 154:
		yyVAL.item = yyS[yypt-0].item
	case 155:
		yyVAL.item = yyS[yypt-0].item
	case 156:
		yyVAL.item = yyS[yypt-0].item
	case 157:
		yyVAL.item = yyS[yypt-0].item
	case 158:
		yyVAL.item = yyS[yypt-0].item
	case 159:
		yyVAL.item = yyS[yypt-0].item
	case 160:
		yyVAL.item = yyS[yypt-0].item
	case 161:
		yyVAL.item = yyS[yypt-0].item
	case 162:
		yyVAL.item = yyS[yypt-0].item
	case 163:
		yyVAL.item = yyS[yypt-0].item
	case 164:
		yyVAL.item = yyS[yypt-0].item
	case 165:
		yyVAL.item = yyS[yypt-0].item
	case 166:
		yyVAL.item = yyS[yypt-0].item
	case 167:
		yyVAL.item = yyS[yypt-0].item
	case 168:
		yyVAL.item = yyS[yypt-0].item
	case 169:

		{
			yyVAL.item = &updateStmt{tableName: yyS[yypt-2].item.(string), list: yyS[yypt-1].item.([]assignment), where: yyS[yypt-0].item.(*whereRset).expr}
		}
	case 170:

		{
			yyVAL.item = nowhere
		}
	case 171:
		yyVAL.item = yyS[yypt-0].item
	case 172:
		yyVAL.item = yyS[yypt-0].item
	case 173:

		{
			var err error
			yyVAL.item, err = newUnaryOperation('^', yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 174:

		{
			var err error
			yyVAL.item, err = newUnaryOperation('!', yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 175:

		{
			var err error
			yyVAL.item, err = newUnaryOperation('-', yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 176:

		{
			var err error
			yyVAL.item, err = newUnaryOperation('+', yyS[yypt-0].item)
			if err != nil {
				yylex.(*lexer).err("%v", err)
				goto ret1
			}
		}
	case 177:

		{
			yyVAL.item = &whereRset{expr: yyS[yypt-0].item.(expression)}
		}
	}
	goto yystack /* stack new state and value */
}
